/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DealRoomEscrow {
  export type DealStruct = {
    maker: AddressLike;
    taker: AddressLike;
    makerToken: AddressLike;
    takerToken: AddressLike;
    makerAmount: BigNumberish;
    takerAmount: BigNumberish;
    status: BigNumberish;
    takerDeadline: BigNumberish;
    arbiterDeadline: BigNumberish;
  };

  export type DealStructOutput = [
    maker: string,
    taker: string,
    makerToken: string,
    takerToken: string,
    makerAmount: bigint,
    takerAmount: bigint,
    status: bigint,
    takerDeadline: bigint,
    arbiterDeadline: bigint
  ] & {
    maker: string;
    taker: string;
    makerToken: string;
    takerToken: string;
    makerAmount: bigint;
    takerAmount: bigint;
    status: bigint;
    takerDeadline: bigint;
    arbiterDeadline: bigint;
  };
}

export interface DealRoomEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ARBITER_TIMEOUT"
      | "MAX_TAKER_DEADLINE_DURATION"
      | "approveDeal"
      | "arbiter"
      | "claimArbiterTimeout"
      | "claimMakerTimeout"
      | "createDeal"
      | "dealCount"
      | "deals"
      | "fundDeal"
      | "getDeal"
      | "rejectDeal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealCompleted"
      | "DealCreated"
      | "DealFunded"
      | "DealRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ARBITER_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TAKER_DEADLINE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "arbiter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimArbiterTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMakerTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeal",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "dealCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "deals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fundDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectDeal",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ARBITER_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TAKER_DEADLINE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbiter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimArbiterTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMakerTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dealCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rejectDeal", data: BytesLike): Result;
}

export namespace DealCompletedEvent {
  export type InputTuple = [dealId: BigNumberish];
  export type OutputTuple = [dealId: bigint];
  export interface OutputObject {
    dealId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCreatedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    maker: AddressLike,
    makerToken: AddressLike,
    makerAmount: BigNumberish,
    takerToken: AddressLike,
    takerAmount: BigNumberish,
    allowedTaker: AddressLike,
    takerDeadline: BigNumberish
  ];
  export type OutputTuple = [
    dealId: bigint,
    maker: string,
    makerToken: string,
    makerAmount: bigint,
    takerToken: string,
    takerAmount: bigint,
    allowedTaker: string,
    takerDeadline: bigint
  ];
  export interface OutputObject {
    dealId: bigint;
    maker: string;
    makerToken: string;
    makerAmount: bigint;
    takerToken: string;
    takerAmount: bigint;
    allowedTaker: string;
    takerDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealFundedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    taker: AddressLike,
    arbiterDeadline: BigNumberish
  ];
  export type OutputTuple = [
    dealId: bigint,
    taker: string,
    arbiterDeadline: bigint
  ];
  export interface OutputObject {
    dealId: bigint;
    taker: string;
    arbiterDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRefundedEvent {
  export type InputTuple = [dealId: BigNumberish];
  export type OutputTuple = [dealId: bigint];
  export interface OutputObject {
    dealId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DealRoomEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): DealRoomEscrow;
  waitForDeployment(): Promise<this>;

  interface: DealRoomEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ARBITER_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MAX_TAKER_DEADLINE_DURATION: TypedContractMethod<[], [bigint], "view">;

  approveDeal: TypedContractMethod<
    [dealId: BigNumberish],
    [void],
    "nonpayable"
  >;

  arbiter: TypedContractMethod<[], [string], "view">;

  claimArbiterTimeout: TypedContractMethod<
    [dealId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimMakerTimeout: TypedContractMethod<
    [dealId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDeal: TypedContractMethod<
    [
      makerToken: AddressLike,
      makerAmount: BigNumberish,
      takerToken: AddressLike,
      takerAmount: BigNumberish,
      allowedTaker: AddressLike,
      takerDeadlineDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  dealCount: TypedContractMethod<[], [bigint], "view">;

  deals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        maker: string;
        taker: string;
        makerToken: string;
        takerToken: string;
        makerAmount: bigint;
        takerAmount: bigint;
        status: bigint;
        takerDeadline: bigint;
        arbiterDeadline: bigint;
      }
    ],
    "view"
  >;

  fundDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  getDeal: TypedContractMethod<
    [dealId: BigNumberish],
    [DealRoomEscrow.DealStructOutput],
    "view"
  >;

  rejectDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ARBITER_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TAKER_DEADLINE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "arbiter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimArbiterTimeout"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimMakerTimeout"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDeal"
  ): TypedContractMethod<
    [
      makerToken: AddressLike,
      makerAmount: BigNumberish,
      takerToken: AddressLike,
      takerAmount: BigNumberish,
      allowedTaker: AddressLike,
      takerDeadlineDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dealCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        maker: string;
        taker: string;
        makerToken: string;
        takerToken: string;
        makerAmount: bigint;
        takerAmount: bigint;
        status: bigint;
        takerDeadline: bigint;
        arbiterDeadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish],
    [DealRoomEscrow.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DealCompleted"
  ): TypedContractEvent<
    DealCompletedEvent.InputTuple,
    DealCompletedEvent.OutputTuple,
    DealCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DealCreated"
  ): TypedContractEvent<
    DealCreatedEvent.InputTuple,
    DealCreatedEvent.OutputTuple,
    DealCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DealFunded"
  ): TypedContractEvent<
    DealFundedEvent.InputTuple,
    DealFundedEvent.OutputTuple,
    DealFundedEvent.OutputObject
  >;
  getEvent(
    key: "DealRefunded"
  ): TypedContractEvent<
    DealRefundedEvent.InputTuple,
    DealRefundedEvent.OutputTuple,
    DealRefundedEvent.OutputObject
  >;

  filters: {
    "DealCompleted(uint256)": TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;
    DealCompleted: TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;

    "DealCreated(uint256,address,address,uint256,address,uint256,address,uint256)": TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;
    DealCreated: TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;

    "DealFunded(uint256,address,uint256)": TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;
    DealFunded: TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;

    "DealRefunded(uint256)": TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;
    DealRefunded: TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;
  };
}
